class people::jgrau::vim {
  vim::bundle { [
    'rodjek/vim-puppet',
    'tpope/vim-fugitive',
    'tpope/vim-liquid',
    'tpope/vim-markdown',
    'tpope/vim-haml',
    'pangloss/vim-javascript',
    'kchmck/vim-coffee-script',
    'vim-ruby/vim-ruby',
    'tpope/vim-rails',
    'tpope/vim-cucumber',
    'msanders/snipmate.vim',
    'scrooloose/nerdtree',
    'wincent/Command-T',
    'tomtom/tcomment_vim',
    'mileszs/ack.vim',
    'tpope/vim-bundler',
    'rizzatti/funcoo.vim',
    'rizzatti/dash.vim',
    'vim-scripts/Toggle',
    'bling/vim-airline',
    'altercation/vim-colors-solarized',
    'tpope/vim-surround',
    'tpope/vim-repeat',
    'nelstrom/vim-textobj-rubyblock',
    'kana/vim-textobj-user',
    'tpope/vim-unimpaired',
    'godlygeek/tabular',
    'scrooloose/syntastic',
    'sjl/gundo.vim'
  ]: }
}
