class people::jgrau::vim {
  include vim

  vim::bundle { [
    'tpope/vim-fugitive',
    'tpope/vim-markdown',
    'tpope/vim-haml',
    'tpope/vim-rails',
    'tpope/vim-cucumber',
    'tpope/vim-bundler',
    'tpope/vim-surround',
    'tpope/vim-repeat',
    'tpope/vim-unimpaired',
    'tpope/vim-abolish',
    'tpope/vim-sleuth',
    'tpope/vim-commentary',
    'tpope/vim-endwise',
    'tpope/vim-dispatch',
    'tpope/vim-ragtag',
    'tpope/vim-sensible',
    'gcmt/wildfire.vim',
    'vim-ruby/vim-ruby',
    'rodjek/vim-puppet',
    'scrooloose/nerdtree',
    'scrooloose/syntastic',
    'rizzatti/funcoo.vim',
    'rizzatti/dash.vim',
    'pangloss/vim-javascript',
    'kchmck/vim-coffee-script',
    'mileszs/ack.vim',
    'vim-scripts/Toggle',
    'bling/vim-airline',
    'altercation/vim-colors-solarized',
    'nelstrom/vim-textobj-rubyblock',
    'kana/vim-textobj-user',
    'godlygeek/tabular',
    'kien/ctrlp.vim',
    'skalnik/vim-vroom',
    'sunaku/vim-ruby-minitest',
    'vim-scripts/taglist.vim',
    'majutsushi/tagbar',
    'tomtom/tlib_vim', # required by snipmate
    'MarcWeber/vim-addon-mw-utils', # required by snipmate
    'garbas/vim-snipmate',
    'honza/vim-snippets',
    'nelstrom/vim-visual-star-search',
    'ervandew/supertab',
    'AndrewRadev/splitjoin.vim',
    'othree/html5.vim',
    'benmills/vimux',
    'thoughtbot/vim-rspec',
    'rainerborene/vim-reek',
    'mattn/webapi-vim',
    'codegram/vim-codereview',
    'mmozuras/vim-github-comment',
    'jgdavey/tslime.vim',
    'toyamarinyon/vim-swift',
    'takac/vim-hardtime',
    'christoomey/vim-tmux-navigator',
    'tpope/vim-vinegar',
    'jeffkreeftmeijer/vim-numbertoggle',
    'skwp/greplace.vim',
    'nelstrom/vim-qargs',
    'dkprice/vim-easygrep',
    'rking/ag.vim',
    'Valloric/YouCompleteMe'
  ]: }
}
