class people::jgrau::vim {
  include vim

  vim::bundle { [
    'tpope/vim-fugitive',
    'tpope/vim-markdown',
    'tpope/vim-haml',
    'tpope/vim-rails',
    'tpope/vim-cucumber',
    'tpope/vim-bundler',
    'tpope/vim-surround',
    'tpope/vim-repeat',
    'tpope/vim-unimpaired',
    'tpope/vim-abolish',
    'tpope/vim-sleuth',
    'tpope/vim-commentary',
    'tpope/vim-endwise',
    'tpope/vim-dispatch',
    'tpope/vim-ragtag',
    'tpope/vim-sensible',
    'vim-ruby/vim-ruby',
    'rodjek/vim-puppet',
    'scrooloose/nerdtree',
    'scrooloose/syntastic',
    'rizzatti/funcoo.vim',
    'rizzatti/dash.vim',
    'pangloss/vim-javascript',
    'kchmck/vim-coffee-script',
    'mileszs/ack.vim',
    'bling/vim-airline',
    'altercation/vim-colors-solarized',
    'nelstrom/vim-textobj-rubyblock',
    'kana/vim-textobj-user',
    'godlygeek/tabular',
    'kien/ctrlp.vim',
    'sunaku/vim-ruby-minitest',
    'vim-scripts/taglist.vim',
    'majutsushi/tagbar',
    'AndrewRadev/splitjoin.vim',
    'othree/html5.vim',
    'christoomey/vim-tmux-navigator',
    'dkprice/vim-easygrep',
    'rking/ag.vim',
    'terryma/vim-expand-region',
    'gregsexton/gitv',
    'janko-m/vim-test',
    'benmills/vimux',
    'kikijump/tslime.vim',
    'ervandew/supertab',
    'benekastah/neomake'
  ]: }
}
